### ISSUE TITLE
Error Compiling for board MKR WiFi 1010

### ISSUE THREAD

**Issue by liuyinze** [khoih-prog/WebSockets2_Generic#46] opened 2022-07-26 08:47 UTC
### Describe the bug

I am currently trying with this library and other dependent libraries which have been installed as well. The first 2 errors are the following. I really don't know how to fix this...
I didn't define the define.h as you did in the example. Is that very necessary to do this?

### Actual behavior

But something wrong happened and I don't know why...

### Debug and AT-command log (if applicable)

C:\Users\yil\OneDrive - Software AG\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/server.hpp:84:51: error: expected ')' before '*' token
       WebsocketsServer(network2_generic::TcpServer* server = new WSDefaultTcpServer);
                                                   ^
C:\Users\yil\OneDrive - Software AG\Documents\Arduino\libraries\WebSockets2_Generic\src/Tiny_Websockets_Generic/server.hpp:100:25: error: 'TcpServer' in namespace 'websockets2_generic::network2_generic' does not name a type
       network2_generic::TcpServer* _server;
                         ^~~~~~~~~

### Information

Please ensure to specify the following:

* Arduino IDE version 1.8.19 
* `STM32`
* We just wanna open a websocket port using "client" so that the msg sent from server could be obtained.

**Comment by khoih-prog** [comment] 2022-07-26 16:36
First use an example to compile / test. After OK and being comfortable, then moving on to **slowly adapt / add your code into the example**. The `defines.h` is **important**, just read, understand and remove only the **unnecessary portions** of it.

I've just compile the [**SAMD_WiFi101-AdvancedWebServer** example](https://github.com/khoih-prog/WebSockets2_Generic/tree/master/examples/Generic/WiFi101/SAMD/SAMD_WiFi101-AdvancedWebServer) without error.

I'm closing the issue now as this is not a bug of the library, and suggest next time, post on [Discussions](https://github.com/khoih-prog/WebSockets2_Generic/discussions) **whenever you're not certain that it's a library's bug**.

![Selection_022](https://user-images.githubusercontent.com/57012152/181060584-2fde814f-2838-442f-8db1-0eb18497d2f2.png)

**Closed by khoih-prog** 2022-07-26 16:36 UTC
